--union it is used to combine values from both tables
--it removes duplicates

CREATE TABLE s1(SNO number(3),SNAME VARCHAR2(20),SCITY VARCHAR2(20));

INSERT ALL 
INTO s1 VALUES(100,'NOZI','BHOPAL')
INTO s1 VALUES(101,'POLI','VIDISHA')
INTO s1 VALUES(102,'ENOCK','BUMBAI')
INTO s1 VALUES(103,'MIN','INDORE')
SELECT * FROM dual;


SELECT * FROM s1;

CREATE TABLE s2(SNO number(3),SNAME VARCHAR2(20),SCITY VARCHAR2(20));

INSERT ALL
INTO s2  VALUES(100,'NOZI','BHOPAL')
INTO s2 VALUES(104,'SKS','ZIM')
SELECT * FROM dual;


SELECT *  FROM s1 
UNION 
SELECT * FROM s2;


CREATE TABLE s3(SNO number(3),SNAME VARCHAR2(20),SCITY VARCHAR2(20),COUNTERY VARCHAR2(20));

INSERT ALL
INTO s3  VALUES(105,'NAR','PUNE','INDIA')
SELECT * FROM dual;

SELECT * FROM s3;

SELECT * FROM s2
UNION
SELECT SNO,SNAME,SCITY FROM s3;
 
 
SELECT * FROM s2--SNO SNAME SCITY
UNION
SELECT SNAME,SCITY,SNO FROM s3;--SNAME, SCITY, SNO

--AUBUCUDUEUF we can combain multipal table 


--UNION ALL it is use to combaine two tables
--it contanins duplicates

SELECT * FROM s1
UNION ALL
SELECT * FROM s2;

--INTERSECT it is used to return common records

SELECT * FROM s1
INTERSECT
SELECT * FROM s2;

--MINUS

SELECT * FROM s1
MINUS
SELECT * FROM s2;

SELECT * FROM s2
MINUS
SELECT * FROM s1;

SELECT * FROM s1
UNION
SELECT * FROM s2
UNION
SELECT * FROM s3;


 








